In [3]:
import numpy as np

# Use argmax

In [4]:
users = np.array(['rex','rana','ali'])
rank = np.array([-1,0,0.5])

In [5]:
x= np.argmax(rank)
users[x]


'ali'

## How to sort an array and desort with numpy

In [6]:
y = np.argsort(rank)[::-1]
y

array([2, 1, 0])

In [7]:
z = users[y]
z

array(['ali', 'rana', 'rex'], dtype='<U4')

# Use vectorize for change custom for all item in array


In [8]:
y = [1,2,3,4,5,6]


```
use python solution
```

In [9]:
#1
x_1 = [str(item) for item in y]
x_1

['1', '2', '3', '4', '5', '6']

In [10]:
#2
x_2 = []
for item in y:
    x_2.append(str(item))
x_2

['1', '2', '3', '4', '5', '6']

In [11]:
#3 functional 
x_3 = list(map(str,y))
x_3

['1', '2', '3', '4', '5', '6']

# Use Numpy to more custome 
```
first make function which you want
make vectorizer from it
pass array to vectorize function
```

In [12]:
def changer (item):
    return f"item_{item}"
v = np.vectorize(changer)
v(y)

array(['item_1', 'item_2', 'item_3', 'item_4', 'item_5', 'item_6'],
      dtype='<U6')

## use Where function of Numpy 

In [13]:
a = np.arange(9)

In [16]:
#put just condition and item which match condition 
b = np.where(a>5)
b

(array([6, 7, 8]),)

In [21]:
# find and map such ternary condition 
c= np.where(a>5, True , False)
c
a[c]

array([6, 7, 8])

### Copy and View in Numpy ----

In [23]:
#there are three type of copy here none - shallow -- deep